### ISSUE TITLE
WooCommerce CSS improvements/mobile-first

### ISSUE THREAD

**Issue by seothemes** [studiopress/genesis-sample#103]
https://github.com/copyblogger/genesis-sample/blob/develop/lib/woocommerce/genesis-sample-woocommerce.css#L201-L219

Lines 201 to 206 can be combined with lines 214 to 219.

Also, media queries should be converted to mobile-first to match style.css

**Comment by nickcernis** [comment]
Closing out. This was fixed in https://github.com/studiopress/genesis-sample/pull/104.
