### ISSUE TITLE
Gutenberg: review Atomic styling

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#118]
If we keep Atomic Blocks elements, noting we'll need to adjust styling for those custom blocks.

For example, link hover styling is currently applied via drop-shadow on the featured posts block, causing the underline to jump:

![hover](https://user-images.githubusercontent.com/647669/45963932-b1414300-c024-11e8-99fe-0b989ed4d227.gif)

**Comment by nickcernis** [comment]
Moving to the backlog milestone for now; we don't currently intend to review for 2.7.

**Comment by dreamwhisper** [comment]
This is no longer an issue in the current AB version.
