### ISSUE TITLE
Vendor extensions

### ISSUE THREAD

**Issue by bgardner** [studiopress/genesis-sample#123]
Thinking that some of the vendor extensions for transitions, border-box, and fadeins can probably be removed. @nickcernis care to take a look?

**Comment by nickcernis** [comment]
@bgardner Sure! I think we should automate this so we don't have to review this manually each time. I've created this PR for that purpose: https://github.com/studiopress/genesis-sample/pull/124.

It means we can type `npm run autoprefixer` and the stylesheet will automatically be corrected to add/remove required prefixes.

It uses the same supported browsers that WP lists to figure out which prefixes to use: https://make.wordpress.org/core/handbook/best-practices/browser-support/.

It's the same script we'll be using in Genesis, so makes sense to me to have it in child themes too.

If you're happy with this approach, I'll merge the PR and run the linter and autoprefixer on the stylesheet in a separate commit.

**Comment by bgardner** [comment]
Yep, works for me. Just don't want to have unnecessary stuff in there.  :-)

**Comment by nickcernis** [comment]
Vendor prefixes updated in https://github.com/studiopress/genesis-sample/commit/fc0688b2f0c5997af2b073b501f07fbcdfbe7777.
