### ISSUE TITLE
Errors in CSS

### ISSUE THREAD

**Issue by iamkunaldesai** [studiopress/genesis-sample#133]
```
<div class="archive-pagination pagination">
   <div class="pagination-previous alignleft">
      <a href="https://kunaldesai.blog/" >&laquo; Previous</a>
   </div>
   <div class="pagination-next alignright">
      <a href="https://kunaldesai.blog/page/3/" >Next &raquo;</a>
   </div>
</div>
```

There is no li in the code but it exists in CSS.

Updated code:

.archive-pagination a {
	background-color: #c3251d;
	color: #fff;
	font-size: 20px;
	font-size: 2.0rem;
}

.archive-pagination a:focus,
.archive-pagination a:hover,
.archive-pagination **a:active** {
	background-color: #fff;
	color: #c3251d;
	text-decoration: none;
}

**Comment by bgardner** [comment]
There are two pagination options in Genesis: Previous/Next (which you have shown as example) and then Numeric (which outputs a list, as seen below)

![genesis-list](https://user-images.githubusercontent.com/486261/48491207-a61cbf00-e7ec-11e8-9470-2ab8d5f2649d.jpg)

**Comment by iamkunaldesai** [comment]
Am talking about Genesis Sample CSS not Genesis.

**Comment by bgardner** [comment]
I understand that, but the option exists in Genesis with any theme being active.
