### ISSUE TITLE
Pullquote colors

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#134]
For https://github.com/studiopress/genesis-sample/commit/2f0671b204a2d8c044b79842603c9b406e826d71, I think we should leave out the background and text color since the options we specified [here](https://github.com/studiopress/genesis-sample/blob/develop/lib/gutenberg/init.php#L103-L121) are options for these.

**Comment by nickcernis** [comment]
@dreamwhisper If there's no background color by default, what would someone see if they select the “solid color” pullquote variation that differentiates it from the regular pullquote?

**Comment by nickcernis** [comment]
I've updated pullquote colors in 8a8d84b6c8808e7a52fb45b082e418be63176c82 to act as follows:

- The default pullquote style has no background.
- The “solid color” pullquote variant has a `#333` background. This is to differentiate it from the regular pullquote, and in case someone has solid color pullquotes and switches theme. (If we set no background color by default, they'd lose the background styling and have to set colors manually after switching theme.)
- Setting the text color of either pullquote now applies that color to `p` and `cite` inside the quote.
- Setting the “main” color of the normal pullquote variation applies a top and bottom border to that pullquote of the selected color. (Gutenberg adds an inline `border-color` in the style attribute of the pullquote block If the “main” color is set for a regular pullquote, or an inline `background-color` for the “solid color” variation.)
- Setting the “main” color of the “solid color” pullquote variation changes the solid color background.

@dreamwhisper Does that seem good? Is there anything we could improve there?

Examples of variations:

### Regular pullquote (no border)

<img width="1134" alt="gutenberg_optimized" src="https://user-images.githubusercontent.com/647669/48694948-0a20f800-ebde-11e8-98e6-45b27c45ec1c.png">

### Regular pullquote with “main color” set to dark gray (adds border)

<img width="1214" alt="gutenberg_optimized" src="https://user-images.githubusercontent.com/647669/48695015-39d00000-ebde-11e8-9d71-11d33b97f877.png">

### Regular pullquote with custom main color and text color

<img width="1145" alt="gutenberg_optimized" src="https://user-images.githubusercontent.com/647669/48695062-6257fa00-ebde-11e8-945b-510cb22d60b8.png">

### “Solid color” pullquote variation default, followed by custom text and main color

<img width="1527" alt="gutenberg_optimized" src="https://user-images.githubusercontent.com/647669/48695118-8e737b00-ebde-11e8-98b3-5f244bea973a.png">

**Comment by nickcernis** [comment]
Closing as this is now in the develop branch in Sample and our other Gutenberg Optimized themes, and has been tested in those too.
