### ISSUE TITLE
menu-highlight background hover color appearing on mobile menu with custom colour.

### ISSUE THREAD

**Issue by jamiemitchell** [studiopress/genesis-sample#151]
When setting a custom color, the menu-highlight button hover color state also appears in the mobile menu.
![screen shot 2018-12-15 at 10 04 15](https://user-images.githubusercontent.com/3365863/50034446-eae87f80-0050-11e9-826e-449536c97d14.png)

**Comment by nickcernis** [comment]
Thanks for this report, @jamiemitchell. Should be fixed in https://github.com/studiopress/genesis-sample/pull/155.
