### ISSUE TITLE
Potentially reinstate column classes

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#152]
Column classes do not work in 2.7.0. https://demo.studiopress.com/genesis-sample/columns/.

Looks like they were removed in 59d089fd7d54bb99f64b5fe9279c8f56e785b734.

@bgardner Can you remember if this was on purpose (because Gutenberg has column blocks, maybe?).

@vfontjr reported this as a regression via Facebook today.

**Comment by bgardner** [comment]
Yes, I think I removed them because—at the time—I thought the columns block would replace it.

**Comment by nickcernis** [comment]
Ok, thanks for the info! Any feelings about whether we should deprecate Genesis column classes in favor of the columns block or not?

Pluses:
- Less CSS to include and maintain.
- The Columns block is (or should be) more intuitive than CSS classes.
- People can still add the CSS snippet to their theme if they want it. https://my.studiopress.com/documentation/usage/genesis-features/use-content-column-classes/

Downsides:
- Those not on WP 5.0 or  won't have a built-in easy way to make columns.
- Removing it would require updating [the docs](https://my.studiopress.com/documentation/usage/genesis-features/use-content-column-classes/) to mention that some themes don't have support for column classes.

cc @dreamwhisper @susannelson for your thoughts too in case you want to share them.

**Comment by nickcernis** [comment]
> fwiw, the Gutenberg stylesheet only loads if the post/page was created in the block editor

This is not currently the case. (Blocks can appear on archives too, so the Gutenberg stylesheet always loads rather than attempting to loop through all posts to determine if it's needed.)

https://github.com/studiopress/genesis-sample/blob/220dcdc15779342ff8a102a47c09fa5d4d97fda9/lib/gutenberg/init.php#L11-L28

> Also the class names are different than the traditional Genesis column classes, aren't they?

Yes, so it would be possible to add them back without conflict if we want to.

**Comment by dreamwhisper** [comment]
If we're using this as a base/starter theme, we could leave them out and update docs, but I would recommend against removing them for any other themes we update. 

If someone elects to update the entire theme rather than just add the Gutenberg editor folder, they'll be left with broken columns if they are using them. This is a potential issue with Sample as well, but I can understand the reasoning for removal.

We do need to rebuild the columns page on the Sample demo with the block editor if we elect to remove them now.

**Comment by bgardner** [comment]
I think for now, and the sake of others, we should add the CSS back into Sample, tag it 2.7.1, and call it a day.
