### ISSUE TITLE
Breadcrumbs settings

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#164]
We're removing the breadcrumbs on the homepage:

https://github.com/studiopress/genesis-sample/blob/develop/template-blocks.php#L49-L50

But, there are still settings for these. (Noting there are some themes that have done this, but it is better UX to not have settings for something that doesn't exist)

A better method would to allow the breadcrumb, but fit it into the current design. This way, we don't need to deal with setting removal or changes.

**Comment by nickcernis** [comment]
We decided to remove the breadcrumbs and breadcrumbs front page option for the Blocks page template.

I confirmed the breadcrumb settings no longer appear after https://github.com/studiopress/genesis-sample/pull/176.

<img width="286" alt="customize__new_homepage" src="https://user-images.githubusercontent.com/647669/51118750-6769ac00-1811-11e9-855a-55cbde177e80.png">
