### ISSUE TITLE
Columns and content width

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#165]
@ 960px the content width is 65%, but this causes the content to be quite narrow before it increases again, making the content narrower than it should be.

![narrow](https://user-images.githubusercontent.com/1271053/50360893-ae74c200-052f-11e9-9431-0321cf40085f.png)

**Comment by nickcernis** [comment]
Tested as part of https://github.com/studiopress/genesis-sample/pull/175.
