### ISSUE TITLE
White screen when “Add new” on reusable Blocks screen

### ISSUE THREAD

**Issue by mjsdiaz** [studiopress/genesis-sample#168]
I get a white screen when i try to “Add new” on the reusable Blocks screen.
1. I made 2 resuable blocks using a Paragraph block and the second one was an Image block.
2. I went to the Blocks page using the Manage All Reusable Blocks link in the Reusable Blocks section of the blocks menu.
3. When I click on either of the blocks, I am able to edit them.
4. When I click “Add new” from the Blocks screen, I get a white screen.

**Comment by nickcernis** [comment]
I wasn't able to reproduce this so far, @mjsdiaz. I'm able to create reusable blocks and click “Add New” without seeing a white screen.

Do you only see this with Genesis Sample active?

Do you see any fatal errors in your PHP error log, or errors in the JavaScript console when you see the white screen?

**Comment by mjsdiaz** [comment]
Thanks, @nickcernis . From more testing, it appears it's a WordPress issue, and not just Genesis. The white screen on the "Add New" blocks screen happens on new installs, regardless of the theme. 
But adding the Classic Editor plugin and setting it to “Allow Users to Switch Editors”, allows the Add New Block page to show.

**Comment by nickcernis** [comment]
Thanks for following up, @mjsdiaz. During Gutenberg's development there were several issues relating to ModSecurity or Cloudflare configurations that could cause blank screens ([example 1](https://github.com/WordPress/gutenberg/issues/9979), [others here](https://github.com/WordPress/gutenberg/search?q=%22blank+screen%22&unscoped_q=%22blank+screen%22&type=Issues)). It might be worth reviewing those just in case they help to reveal more.
