### ISSUE TITLE
Remove '/contact' links from homepage onboarding content

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#181]
Homepage onboarding content features relative links to a `/contact` URL, such as this one:

https://github.com/studiopress/genesis-sample/blob/71e85ddd4ca4229a92d5377d847183c1e4947c43/config/import/content/homepage.php#L89

Even though these links are intended to be replaced by site owners, we should replace them in demo content with `#` so they don't 404.

**Comment by dreamwhisper** [comment]
@nickcernis It's just the one link, correct? I think the others are all `#`.

**Comment by nickcernis** [comment]
@dreamwhisper This one too:

https://github.com/studiopress/genesis-sample/blob/71e85ddd4ca4229a92d5377d847183c1e4947c43/config/import/content/homepage.php#L111
