### ISSUE TITLE
Create a page-templates folder for page templates

### ISSUE THREAD

**Issue by bradpotter** [studiopress/genesis-sample#183]
Consider creating a page-templates folder and moving following templates to the new folder.
Rename "template-blocks.php" to "blocks.php"
Rename "page_landing.php" to "landing.php"
Change references to template-blocks.php in onboarding.php 

This would help bring the sample theme in alignment with the folder structure of latest theme release from SP (Revolution Pro)

**Comment by dreamwhisper** [comment]
@bradpotter Thanks for opening this. It is planned :)

**Comment by dreamwhisper** [comment]
PR at https://github.com/studiopress/genesis-sample/pull/193
