### ISSUE TITLE
Onboarding: add other pages

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#184]
Add the pages from https://demo.studiopress.com/genesis-sample/ (or a subset) automatically during onboarding.

**Comment by dreamwhisper** [comment]
Current plan is for these pages:

```
Homepage
Features
- Block Editor (with columns, pricing, quotes)
- Layouts
-- Content / Sidebar (standard page content, not blog)
-- Sidebar / Content (standard page content, not blog)
-- Full-width Content (standard page content, not blog)
About
Contact
```

**Comment by dreamwhisper** [comment]
Imported pages in PR:
- About
- Contact
- Block Examples
- Landing

We can update once we can do layouts with a future Genesis release.

**Comment by dreamwhisper** [comment]
Closed with https://github.com/studiopress/genesis-sample/pull/194
