### ISSUE TITLE
Block Editor: automatically generate inline CSS for editor theme supports

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#187]
In recent (unreleased) StudioPress theme updates, we've started generating Gutenberg inline CSS code on the front and back that can be inferred automatically from theme supports such as `editor-font-sizes` and `editor-color-palettes`.

I'd like to explore doing the same in Genesis Sample to reduce the amount of Gutenberg-related CSS people have to write when using Sample as a starting point for their themes.

**Comment by wpfangirl** [comment]
That sounds like a wonderful idea.

**Comment by jb510** [comment]
This sounds scary...  

I'm not necessarily opposed to it, but I am concerned with anything generating inline styles that might over-ride existing child theme CSS.

What "inline CSS" specifically is going to get injected based on theme supports?  (I obviously haven't seen the unreleased updates)

**Comment by nickcernis** [comment]
@jb510 Nothing scary, just removing the need to add CSS like this manually:

- https://github.com/studiopress/genesis-sample/blob/71e85ddd4ca4229a92d5377d847183c1e4947c43/lib/gutenberg/front-end.css#L4-L18

As that CSS can already be inferred from https://github.com/studiopress/genesis-sample/blob/71e85ddd4ca4229a92d5377d847183c1e4947c43/config/editor-font-sizes.php#L13-L34.

Same with `editor-color-palette`.

Also, in case you hadn't spotted it, this proposal is for the Genesis Sample repo. You could remove it if you didn't want to use it, and it won't affect Genesis itself/other child themes at present.

**Comment by jb510** [comment]
Ugh, I'll be more careful, that's the second time I mistook an issue for Genesis Sample as an issue for Genesis core...  Sorry.

**Comment by nickcernis** [comment]
@jb510 No problem! Thanks for taking an interest in this stuff and for sharing your thoughts.

**Comment by nickcernis** [comment]
Work on this has now been merged into develop in https://github.com/studiopress/genesis-sample/pull/198.

This will form part of the Genesis Sample 2.9.0 release planned for late this week.
