### ISSUE TITLE
Update Child theme constants to use new helper functions

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#188]
Update method used in https://github.com/studiopress/genesis-sample/blob/develop/functions.php#L16-L19 to use the style.css header theme info.

Will also need to update script/style versions.

**Comment by nickcernis** [comment]
We plan to review this after work in Genesis on a potential new `genesis_get_theme_version()` and `genesis_get_theme_handle()` function is complete: https://github.com/studiopress/genesis/pull/2199.

**Comment by nickcernis** [comment]
We updated constants in functions.php to pull from the stylesheet header in Genesis Sample 2.9.0, and deprecated unused ones.

I'm leaving this open to replace the `CHILD_THEME_HANDLE` and `CHILD_THEME_VERSION` constants to use the new helper functions from Genesis if/when they're available.

**Comment by nickcernis** [comment]
`genesis_get_theme_version()` and `genesis_get_theme_handle()` will land in Genesis 3.0.0 (PR here: https://github.com/studiopress/genesis/pull/2199).

I've added this issue to the Sample 3.0.0 milestone so we can replace constants with those functions.
