### ISSUE TITLE
Wide table spacing differs on front and back end

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#202]
### Front (margin incorrect, tables don't use full width)
![wide tables appear in correct on the front end](https://user-images.githubusercontent.com/647669/54183920-a3359080-44a5-11e9-9050-3e841683a4a7.jpg)

### Back (appears as expected)
![tables appear correctly on the back end](https://user-images.githubusercontent.com/647669/54183928-a761ae00-44a5-11e9-93b8-945dcb0894ca.jpg)

Thanks to Alex Mustin for the report in Slack.

**Comment by dreamwhisper** [comment]
https://stackoverflow.com/questions/35712461/strange-things-with-negative-margins-on-tables
This seems to work for the alignwide table:
```css
.wp-block-table.alignwide {
    width: calc(100% + 360px);
}
```
