### ISSUE TITLE
Plugins Don't Install During Activation on Localhost using WAMP

### ISSUE THREAD

**Issue by progenthemes** [studiopress/genesis-sample#214]
When I activate the theme on localhost / WAMP the plugins don't install automatically. Is there something I need to change in my WAMP setup or is this something else with the theme?

**Comment by nickcernis** [comment]
Thanks for the report, @progenthemes. Please could you share some extra information to help us look into this?

1. The version of Genesis Sample.
2. The version of Genesis.
3. What does your `config/onboarding.php` file currently look like?
4. Can you install and activate plugins in your WAMP install without error via the regular WordPress plugin admin area?
5. Is the issue that plugins do not install, do not activate, or both?
6. Do you see any errors in the console, in your PHP error log, or in the admin-ajax.php response in your browser's developer tools on the network pane?

**Comment by progenthemes** [comment]
so while unactivating and re-activating to test for errors to answer your questions, it seemed to have worked. Which is weird because I have done quite a bit of troubleshooting doing the same thing and it's never worked. I'll close this for now. Thanks for your response. I'll reach back out if I have any more issues with this.
