### ISSUE TITLE
Review colors & update customizer description text

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#220]
**Describe the bug**
In 2.9, we updated the block colors to use customizer selected colors. 

We need to update the customizer text to reflect that colors now use colors derived from the color selected in the customizer.

**To reproduce**
1. Open the customizer to the colors section.
2. Note that the accent color says it applies to buttons, but `This setting does not apply to buttons created with the Buttons block.`

![sample-colors](https://user-images.githubusercontent.com/1271053/54919662-c6196900-4ed7-11e9-865e-dff107db1b37.png)

`This setting does not apply to buttons created with the Buttons block.` is true since the block buttons use the link color instead, but it is not clear from the customizer text that the link color applies.

We need to:
1) Determine this is the color pattern we would like to use.
2) Update the customizer text to better reflect where it applies.

**Comment by nickcernis** [comment]
I've clarified the text in https://github.com/studiopress/genesis-sample/pull/234, but would appreciate the thoughts of @susannelson and @dreamwhisper.

> We need to: 1. Determine this is the color pattern we would like to use.

I think the pattern is fine for now (button blocks take the link color, other buttons take the accent color). Button blocks are used more like links, so it seems right that they mirror link color. People can continue to set both colors to be the same if they want all buttons to use the same color. I'm open to other options, though, and we might want to review this again when button blocks can appear outside of regular post content.

**Comment by susannelson** [comment]
@nickcernis I think what you have works. 

The only change we might want to make is to say "menu buttons" instead of "the menu button" for consistency.

So:

> Accent Color
> Change the default hover color for button links, menu buttons, and submit buttons. The button block uses the Link Color.

But that's being really nit-picky. It's certainly fine the way it is if you don't agree. :)

**Comment by nickcernis** [comment]
@susannelson Thanks for the feedback — I agree and have made that change in https://github.com/studiopress/genesis-sample/pull/234/commits/dca42e92ec1a7529ef6f86acae9dfa9e71b47b94.
