### ISSUE TITLE
Add full-width page layout meta to imported pages

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#232]
Genesis 2.10.0 will support setting post meta for content imported during one-click theme setup.

`'meta_input' => array( '_genesis_layout' => 'sidebar-content' ),`

We can set page meta for the following pages to make them full-width, instead of setting their `page_template` to `page-templates/blocks.php`.

- Block Content Examples (also remove “Block Content Examples” from page content).
- About Us (also remove “About Us” heading from the page content).

We can leave `page-templates/blocks.php` for the homepage; it removes page title and breadcrumb markup, which is still required there.

**Comment by dreamwhisper** [comment]
Closed with https://github.com/studiopress/genesis-sample/pull/233
