### ISSUE TITLE
font-display

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#249]
Google fonts will soon support [font-display](https://developers.google.com/web/updates/2016/02/font-display) without needing to host the files.

https://twitter.com/szynszyliszys/status/1126261253280649216

PageSpeed Insights currently flags it as something to improve.

Looks like the query param may end up being `&display=swap`:
https://github.com/google/fonts/issues/358#issuecomment-491244758

**Comment by nickcernis** [comment]
Google updated their fonts service and font-display swap is now live:

https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,700&display=swap

(note font-display: swap in the response).

I added this to the 3.0.0 milestone.
