### ISSUE TITLE
Refactor config folder

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#260]
Our current structure looks like this:

```
config
├── accessibility.php
├── block-editor-settings.php
├── child-theme-settings-genesis.php
├── child-theme-settings.php
├── color-palette.php
├── custom-logo.php
├── html5.php
├── import
├── menus.php
├── onboarding.php
├── responsive-menus.php
└── simple-social-icons-settings.php
```

Before the config folder continues to grow, we should consider moving toward a more simple structure like this:

```
config
├── defaults.php // was child-theme-settings.php
├── appearance.php // fonts and colors-> block-editor-settings.php, color-palette.php
├── theme-supports.php // custom-logo.php, html5.php, genesis-accessibility.php, menus.php 
├── import
├── onboarding.php
├── responsive-menus.php
└── simple-social-icons.php // drop '-settings' from the name
```

The main changes are:

- Move all theme-supports into a single file. (This could potentially then be autoloaded by Genesis in the future, removing all `add_theme_support` lines from child themes that want to use the feature.)
- Remove `block-editor-settings.php` in favor of `appearance.php` (or `design.php` or `styles.php`?), where all fonts and colors can be declared.
- Remove '-settings' from filenames, given that all of them contain settings of some kind or other.

Edit:

Noting that `child-theme-settings.php` will have to continue to use that name, as it's hard-coded and auto-loaded by Genesis: https://github.com/studiopress/genesis/blob/8899887473437ba5a0a017b0214da9e17a009677/lib/admin/onboarding/theme-activation.php#L53

**Comment by jb510** [comment]
Love all this.

**Comment by seothemes** [comment]
Looks good. I was going to create a new issue about the web fonts config but this fixes it.

Moving all theme supports to a single file is a great improvement. We did discuss it a while ago but it was decided against - https://github.com/studiopress/genesis/issues/1997#issuecomment-426616609. I think now we can see why it is needed, there are still too many `add_theme_support` calls in functions.php.

All Genesis needs is a simple foreach:

```php
$theme_support = genesis_get_config( 'theme-support' );

foreach ( $theme_support as $feature => $args ) {
	$feature = is_int( $feature ) ? $args : $feature;
	
	add_theme_support( $feature, $args );
}
```
