### ISSUE TITLE
Genesis Sample 3.1 plans

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#275]
This is an umbrella issue for Genesis Sample 3.1 to outline potential features for the next minor version.

1. **Add homepage variation for user to choose during one-click theme setup** (if time allows creation of a second homepage, and pending feature availability in Genesis 3.1).

2. **Add footer widgets during one-click theme setup.** https://demo.studiopress.com/genesis-sample/#genesis-footer-widgets (Genesis 3.1 will allow widget import during onboarding.) See https://github.com/studiopress/genesis-sample/issues/276.

3. **Hide homepage title and breadcrumbs with new Genesis title toggle and breadcrumb toggle features**, instead of using the Blocks template.

4. Tackle any other open Sample issues we have time for. (Submenu position? #261 Sticky header? #269 )

**Comment by seothemes** [comment]
Should also convert arrays to short syntax.
