### ISSUE TITLE
Set an image_size upon theme switch instead of clearing it

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#290]
**Describe the bug**
When activating Genesis Sample, the archive featured image size is cleared:
 
<img width="308" alt="Screen Shot 2019-08-12 at 16 41 51" src="https://user-images.githubusercontent.com/647669/62873903-83d6b400-bd20-11e9-97ce-2727a3858462.png">

We should probably set `image_size` in `config/child-theme-settings.php` to one of the available image sizes instead of clearing it, so that a known size is selected instead of the empty value.

An alternative is to remove the `image_size` key so that it is not overridden.

Reported by @robincornett via Slack.

**To reproduce**
1. Set the archive featured image size in Customize -> Theme Settings -> Archive -> Featured Image Size.
2. Switch to Genesis Sample (or switch to another theme and then back to Sample).
3. The featured image size will be empty.

**Expected behavior**
The default featured image size is one that is available from the drop-down, such as 'thumbnail'.

**Comment by dreamwhisper** [comment]
@nickcernis PR is at https://github.com/studiopress/genesis-sample/pull/292

Noting that [Genesis sets the size the same way](https://github.com/studiopress/genesis/blob/develop/lib/admin/install.php#L49). Thus, this will happen with any theme that doesn't specify an image size if it omits the line or has no theme defaults. We originally copied that over from Genesis for convenience of having the `image_size` line in place.

**Comment by nickcernis** [comment]
> Noting that Genesis sets the size the same way. Thus, this will happen with any theme that doesn't specify an image size if it omits the line or has no theme defaults. (Assuming that none was ever set)

Thanks, @dreamwhisper. Perhaps we should revisit the default for image size in Genesis (and possibly make it 'thumbnail' too) when we look at the settings refactor @nathanrice mentioned under “long term” here: https://github.com/studiopress/genesis/issues/2441

**Comment by dreamwhisper** [comment]
@nickcernis I don't see anything wrong with it being empty per se. Perhaps a "None" or "Select a size" would be a better option than arbitrarily setting a size.

**Comment by robincornett** [comment]
If you do not want to arbitrarily set a size, which I do think makes sense for the Sample theme, I would suggest just not adding a key for it. The setting does not have a none/empty string option, I expect because that is handled by the checkbox setting above (the "Display a featured image" setting). So the empty string, or a "none" choice, is redundant. Not changing what's already set makes more sense (if you go that route, I would suggest also removing the image alignment key, as that's intended for a thumbnail/smaller image display, and quite a few themes will set larger image sizes with center alignment).

**Comment by dreamwhisper** [comment]
@robincornett Just to be clear we were referring to Genesis itself having an empty setting when a theme is first activated, not a child theme. Setting a size in Sample has been completed.

**Comment by robincornett** [comment]
Thanks Jen--just would like to note that it shouldn't be that way in the framework either, as an empty string is not one of the options in the list, and I do not think it should be since the checkbox exists.
