### ISSUE TITLE
Invalid breadcrumbs schema markup

### ISSUE THREAD

**Issue by OksanaRomaniv** [studiopress/genesis-sample#310]
**Describe the bug**
With the recent update, GSC reported invalid breadcrumbs for all parent pages (that have only home page before them in the breadcrumbs list). The error: Missing field "itemListElement". Indeed it's not present on the home page link markup.

**To reproduce**
1. Check the parent page with activated breadcrumbs with the Rich Snippets testing tool

**Expected behavior**
The breadcrumbs have valid SEO markup

**Screenshots**
[error-report](http://i.imgur.com/0AzV7H8.png)

**System information (please complete)**
 - Ubuntu
 - Chrome 77 
 - Genesis 3.1.2 

**Additional context**
The example of invalid markup that is generated on the parent-level page:
````
<div class="breadcrumb" itemprop="breadcrumb" itemscope="" itemtype="https://schema.org/BreadcrumbList">
    <a href="https://home-page" title="Home Page">
        <svg role="img" title="Home Page"><use xlink:href="#icon-home"></use></svg>
    </a> → Adventskalender 2019
</div>
````

**Comment by danishmuneer** [comment]
We are having the same issue and some more (see screenshot below). On top of that, the `genesis_attr_body` is not working. We use it to change the schema attributes on a custom post type and category page. It was working before the last update. 

```
function custom_microdata_schema( $attributes ){
        if( is_singular( 'epkb_post_type_1' ) ) {
                $attributes['itemtype'] = 'https://schema.org/QAPage';
		}	
        if( is_tax( 'epkb_post_type_1_category' ) ) {
                $attributes['itemtype'] = 'https://schema.org/QAPage';
		}
        return $attributes;       
}
add_filter( 'genesis_attr_body', 'custom_microdata_schema' );

```

Here's what we are getting on Google along with the error @OksanaRomaniv  posted...
![1](https://user-images.githubusercontent.com/26395892/65783353-a2044200-e11d-11e9-91c7-65b00961c72a.png)

**Comment by nickcernis** [comment]
This seems specific to Genesis rather than Genesis Sample, but are either of you using Yoast SEO?

Genesis 3.1+ disables Genesis schema.org markup when Yoast is in use, which would affect existing schema.org markup as well as any customized schema.org parameters.

There's a note here with a potential workaround:

https://studiopress.github.io/genesis/developer-features/schema-markup/#compatibility-with-yoast-seo

If you need further help with this, though, I recommend sharing information and example URLs with [StudioPress support](http://my.studiopress.com/help).

**Comment by OksanaRomaniv** [comment]
Hello @nickcernis, I don't use Yoast SEO. The breadcrumbs are outputted by the core Genesis parent theme. All the Genesis microdata for article, header, footer etc is in place.

**Comment by nickcernis** [comment]
Thank you for the information, @OksanaRomaniv.

I'm unable to reproduce this so far. I tried testing a static homepage and latest posts page where only the “Home” link is visible (or unlinked, in the case of the latest posts page).

I do not see “missing field itemListElement” in either case.

Do you see errors when you run the homepage through Google's structured data testing tool? https://search.google.com/structured-data/testing-tool

If so, it would be helpful to share the errors and your test URL with the [StudioPress support team](http://my.studiopress.com/help) so we can look into this.

If not, this may be a false positive, and you could try following up in [Google's webmaster forums](https://support.google.com/webmasters/community) for an explanation as to why you're seeing the warning.

**Comment by jb510** [comment]
@nickcernis fwiw, I’m seeing this search console message too in the last two weeks, in that case on a custom child theme and determined it was low priority so I haven’t actually looked into it yet. It’s is doubtful that it is a child theme issue.  I’ll open an issue on genesis if/when I can reproduce.

**Comment by nickcernis** [comment]
Thanks, @jb510. I'd be interested to learn exactly under what conditions it occurs

**Comment by nickcernis** [comment]
For those affected, @dreamwhisper pointed out that filtering the breadcrumbs could result in this issue.

For example, adding an icon as done here: https://gist.github.com/rickrduncan/47cbbccf4ac804b8e9f0#file-genesis-breadcrumb-fontawesome-php

**Comment by OksanaRomaniv** [comment]
@nickcernis , indeed the home crumb was filtered with `genesis_home_crumb`. The filter replaced not only the link tag markup for the home page but also a wrapping span with `itemprop="itemListElement"`. I'm not sure if this behavior was changed in the recent updates because it previously didn't produce any errors. Thank you for the tip!

**Comment by nickcernis** [comment]
Thanks for the update, @OksanaRomaniv. Credit belongs to @dreamwhisper for that tip, and I'm glad it helped!
