### ISSUE TITLE
Unlink the custom logo

### ISSUE THREAD

**Issue by davidperezgar** [studiopress/genesis-sample#312]
Hello, I'd like to unlink the custom logo, but I don't know how to do it.

There is a filter
`add_filter( 'genesis_seo_title', 'cmk_theme_logo', 10, 3 );`
but it seems that it does not get it.

How can i do it?

**Comment by dreamwhisper** [comment]
@davidperezgar The current Genesis Sample logo functionality uses WordPress functions to show the logo. You can filter `get_custom_logo` to remove or change the link. There's a thread in the WP.org support forums that may be helpful: https://wordpress.org/support/topic/how-to-remove-a-link-from-image-header/

If you need additional help, our [community forums](https://studiopress.community/) would be a great place to get assistance.

**Comment by davidperezgar** [comment]
Thanks Jen! I didn't know that filter, and that's why I couldn't find it.

Thanks!
