### ISSUE TITLE
Update HTML5 supports for WordPress 5.3

### ISSUE THREAD

**Issue by robincornett** [studiopress/genesis-sample#313]
In WordPress 5.3, [new HTML5 theme support parameters](https://make.wordpress.org/core/2019/10/15/miscellaneous-developer-focused-changes-in-5-3/) have been added:

> In HTML5, the type attribute is not required for the <script> and <style> tags. Including the attribute on these tags (type="text/javascript", for example) will trigger a validation warning in HTML validation tools.
> 
> In WordPress 5.3, two new arguments are now supported for the html5 theme feature, script and style. When these arguments are passed, the type attribute will not be output for those tags.

Should `script` and `style` be added to the [HTML5 support in the config](https://github.com/studiopress/genesis-sample/blob/develop/config/theme-supports.php#L20-L26)?

**Comment by nickcernis** [comment]
I think this is a good idea, yes.
