### ISSUE TITLE
category archive does not work

### ISSUE THREAD

**Issue by broros** [studiopress/genesis-sample#329]
category pages do not work if I add a . in Category base

![remove-category-slug-using-dot](https://user-images.githubusercontent.com/598228/72712488-5dffd780-3b28-11ea-9aba-585b745f62e2.png)

**Comment by nickcernis** [comment]
> category pages do not work if I add a . in Category base

A dot on its own is not a valid category base, so you will see the same for all themes including Twenty Twenty.

If you want to use `/%category%/%postname%/` as the custom structure, you can leave the “category base” empty and still access category archives at `/category/your-archive-slug/`.
