### ISSUE TITLE
white space

### ISSUE THREAD

**Issue by broros** [studiopress/genesis-sample#330]
What is this white space at the bottom?

<img width="1328" alt="Screenshot 2020-01-20 at 5 33 57 AM" src="https://user-images.githubusercontent.com/598228/72727016-1b012c80-3b47-11ea-85f3-37a04af8aa2f.png">

All browsers

**Comment by nickcernis** [comment]
@broros I can't reproduce this so far, but I've seen it before from plugins, custom code, or custom content that overflows the container.

Do you have a link to the live site, or steps to reproduce and browser info if you're not using any plugins and haven't modified the theme?

The `site-footer` https://demo.studiopress.com/genesis-sample/ doesn't display this in Chrome if make the background darker, for example:

<img width="839" alt="Screen Shot 2020-01-20 at 14 08 41" src="https://user-images.githubusercontent.com/647669/72728797-76a2d880-3b8e-11ea-9cfb-c3db9f036d2e.png">

**Comment by broros** [comment]
[apicalhealth.com](url)

**Comment by nickcernis** [comment]
Thanks for the link, @broros.

The white space is coming from a tracking pixel provided by this element at the foot of the site:

`<img src="https://analytics.revelhost.net/piwik.php?idsite=4&amp;rec=1" style="border:0" alt="">`

A quick way to diagnose issues like this is to remove elements near the bottom of the site container by selecting them in the Elements window in Chrome and pressing backspace to delete them until the whitespace goes away:

![image-removal](https://user-images.githubusercontent.com/647669/72733126-7fe47300-3b97-11ea-84c6-9056887d0b84.gif)

To fix it you'll need to remove that element or adjust its CSS in a way that does not affect any tracking functionality it provides. (Piwik may be able to advise further about this.)

Just a note that Genesis Sample GitHub issues are for reporting bugs that are specific to the child theme – it is for things you can reproduce only with Genesis Sample in its default state, or for feature requests.

For troubleshooting help with general WordPress issues or site-specific issues, I recommend these resources: https://studiopress.github.io/genesis/contribute/community/

**Comment by broros** [comment]
Thanks
