### ISSUE TITLE
Cover block alignwide pushes beyond site width on iPad Pro

### ISSUE THREAD

**Issue by ninetyninew** [studiopress/genesis-sample#336]
**Describe the bug**
If you use the cover block and use the "Wide Width" setting on the block (applies an alignwide class) then the element is wider than 100% of the site page on iPad Pro using Chrome Debugger, appears to do the same for iPad. Other width settings work fine.

**To reproduce**
1. Add a cover block with background color
2. Apply "Wide Width" setting on the block
3. Look at website within Chrome Debugger selecting iPad Pro/iPad devices

**Expected behavior**
Element is within the site width.

**Screenshots**
![image](https://user-images.githubusercontent.com/56840277/76418389-76f17000-6396-11ea-8b9a-9cbe0cbbd549.png)

**System information (please complete)**
 - Ubuntu 18.04
 - Chrome
 - Latest
 - Genesis Sample 3.2.0

**Comment by nickcernis** [comment]
Thanks for the report. I wasn't able to reproduce this with the above steps in Chrome. The wide width does not overflow the page width for me:

<img width="853" alt="Screen Shot 2020-04-03 at 16 18 50" src="https://user-images.githubusercontent.com/647669/78370496-01f50d00-75c7-11ea-9c59-e92f2f5246d8.png">

Is this still an issue for you?

Is the block inside another block?

Are all plugins disabled?

**Comment by ninetyninew** [comment]
Apologies as this was a while ago I can't recreate the issue but it may have been due to some style tweaks added outside Genesis, I'll close this ticket.
