### ISSUE TITLE
20px editor-font-sizes overridden after 5.9 update

### ISSUE THREAD

**Issue by waybis** [studiopress/genesis-sample#390]
When you select a large 20px font size within the block editor, this is overriden by --wp--preset--font-size--large: 36px; since upgrading to wordpress 5.9

**To reproduce**
1. set font size to large 20 px
2. upgrade to wordpress 5.9

**Expected behavior**
font size should be 20px

**Screenshots**

**System information (please complete)**
 - OS Windows
 - Browser Chrome
 - Version 97.0.4692.99

**Additional context**
appearance.php sets the editor font sizes
possibly related to this [](https://core.trac.wordpress.org/ticket/54782)

**Comment by dreamwhisper** [comment]
Thanks for the report @waybis!

We're currently tracking this issue in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/38252

**Comment by waybis** [comment]
great thanks seems to be in hand! 👍 I'll just avoid 20px for the time being, sounds like it might turn out to be a longish debate.

**Comment by webmandesign** [comment]
Hi there. In the linked Gutenberg issue I've provided an [immediate fix for the issue](https://github.com/WordPress/gutenberg/issues/38252#issuecomment-1024348024). Feel free to use it even as a temporary fix.

**Comment by dreamwhisper** [comment]
Resolved in Core.
