### ISSUE TITLE
Add npm scripts

### ISSUE THREAD

**Issue by nathanrice** [studiopress/genesis-sample#43]
Grunt automates stuff for us, and we have it in place for Genesis as well as most of our plugins. Should be pretty easy to add.

To do: makepot once Grunt is in place.

**Comment by nickcernis** [comment]
Changing to “Add npm scripts” to reflect the discussion in Genesis core: https://github.com/studiopress/genesis/issues/1941.

**Comment by nickcernis** [comment]
npm scripts have now been added. https://github.com/studiopress/genesis-sample/pull/124

Installing npm and using the scripts is also documented in the readme: https://github.com/studiopress/genesis-sample#npm-scripts
