### ISSUE TITLE
Gutenberg Support for Wide Images

### ISSUE THREAD

**Issue by bgardner** [studiopress/genesis-sample#88]
Add support for wide images, galleries, and videos via Gutenberg.

**Comment by bgardner** [comment]
@nickcernis When you have time, this will require some testing. Might require specificity.

For reference:
https://themeshaper.com/2018/02/15/styling-themes-for-gutenberg/
https://github.com/WordPress/gutenberg-starter-theme/blob/master/css/blocks.css

**Comment by nickcernis** [comment]
@bgardner Mostly looks good! A couple of small issues in testing so far:

- https://github.com/copyblogger/genesis-sample/issues/89
- https://github.com/copyblogger/genesis-sample/issues/91

**Comment by nickcernis** [comment]
Wide image/video/gallery support now complete in the beta branch.

https://demo.studiopress.com/genesis-sample-beta/block-unit-test/
