### ISSUE TITLE
Gutenberg: hr style

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#99]
Style `hr.wp-block-separator` same as default `hr` tag.

Also, add to back-end editor styles.

**Comment by nickcernis** [comment]
Work on this is now complete for all three hr block styles, front and back.

Visible at https://demo.studiopress.com/genesis-sample-beta/block-unit-test.

<img width="772" alt="block_unit_test" src="https://user-images.githubusercontent.com/647669/46478858-1dbefd80-c7ee-11e8-8389-8b91fdf837f0.png">
